/**
 * The compile pipeline: Context + resolved targets → generated outputs.
 *
 *   .map ──loader──▶ Context ──adapter──▶ body ──banner──▶ CompiledOutput
 *
 * This module ties an adapter to its configured output path and prepends the
 * "generated — do not edit" banner in the comment style the adapter declares. Writing
 * to disk is the caller's job (the `sync` command), keeping the pipeline pure.
 */

import type { Context } from "./context.ts";
import type { ResolvedCompilerConfig } from "./compiler-config.ts";
import type { AdapterRegistry, BannerStyle } from "./adapters/index.ts";

export interface CompiledOutput {
  readonly target: string;
  /** Output path relative to the project root, from the config. */
  readonly path: string;
  readonly content: string;
}

export interface CompileResult {
  readonly outputs: readonly CompiledOutput[];
  /** Target ids whose adapter could not be resolved. */
  readonly unknownTargets: readonly string[];
}

const BANNER_LINES = [
  "Generated by MAP. Do not edit directly.",
  "Edit the files inside .map/ and run `map sync` to regenerate.",
];

export function compile(
  context: Context,
  config: ResolvedCompilerConfig,
  registry: AdapterRegistry,
): CompileResult {
  const outputs: CompiledOutput[] = [];
  const unknownTargets: string[] = [];

  for (const target of config.targets) {
    const adapter = registry.get(target.adapter);
    if (adapter === undefined) {
      unknownTargets.push(target.id);
      continue;
    }
    const body = adapter.compile(context);
    outputs.push({
      target: target.id,
      path: target.output,
      content: withBanner(body, adapter.bannerStyle),
    });
  }

  return { outputs, unknownTargets };
}

/**
 * Prepend the banner. When the output opens with its own frontmatter block (Cursor's
 * MDC), the banner is inserted *after* that block so the frontmatter stays first.
 */
function withBanner(body: string, style: BannerStyle): string {
  const block = `${banner(style)}\n`;
  const fence = /^---\n[\s\S]*?\n---\n/.exec(body);
  if (fence) {
    return body.slice(0, fence[0].length) + "\n" + block + body.slice(fence[0].length);
  }
  return block + body;
}

function banner(style: BannerStyle): string {
  if (style === "hash") {
    return BANNER_LINES.map((line) => `# ${line}`).join("\n");
  }
  return `<!--\n${BANNER_LINES.map((line) => `  ${line}`).join("\n")}\n-->`;
}
