import { describe, it, expect } from "vitest";
import { mkdtemp, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runCli } from "../src/cli/runner.ts";
import { capture } from "./helpers.ts";

const silent = () => capture();

async function tempProject(): Promise<string> {
  return mkdtemp(join(tmpdir(), "map-sync-"));
}

const OUTPUTS = [
  "CLAUDE.md",
  "AGENTS.md",
  "GEMINI.md",
  ".cursor/rules/map.mdc",
  ".github/copilot-instructions.md",
];

describe("map sync", () => {
  it("compiles .map into every configured target", async () => {
    const dir = await tempProject();
    try {
      await runCli(["init", "--yes"], { cwd: dir, reporter: silent() });
      const code = await runCli(["sync"], { cwd: dir, reporter: silent() });
      expect(code).toBe(0);

      for (const out of OUTPUTS) {
        const content = await readFile(join(dir, out), "utf8");
        expect(content).toContain("Generated by MAP");
      }
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("keeps the Cursor MDC frontmatter first", async () => {
    const dir = await tempProject();
    try {
      await runCli(["init", "--yes"], { cwd: dir, reporter: silent() });
      await runCli(["sync"], { cwd: dir, reporter: silent() });
      const mdc = await readFile(join(dir, ".cursor/rules/map.mdc"), "utf8");
      expect(mdc.startsWith("---\n")).toBe(true);
      expect(mdc.indexOf("Generated by MAP")).toBeGreaterThan(mdc.indexOf("alwaysApply"));
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("fails cleanly when the workspace config is missing", async () => {
    const dir = await tempProject();
    try {
      const reporter = capture();
      const code = await runCli(["sync"], { cwd: dir, reporter });
      expect(code).toBe(1);
      expect(reporter.lines.join("\n")).toContain("map.config.json");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("regenerates outputs when a document changes", async () => {
    const dir = await tempProject();
    try {
      await runCli(["init", "--yes"], { cwd: dir, reporter: silent() });
      await writeFile(
        join(dir, ".map/architecture/README.md"),
        "# Architecture\n\nUNIQUE_MARKER_TOKEN\n",
      );
      await runCli(["sync"], { cwd: dir, reporter: silent() });
      expect(await readFile(join(dir, "CLAUDE.md"), "utf8")).toContain("UNIQUE_MARKER_TOKEN");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("respects per-document target frontmatter", async () => {
    const dir = await tempProject();
    try {
      await runCli(["init", "--yes"], { cwd: dir, reporter: silent() });
      await writeFile(
        join(dir, ".map/prompts/README.md"),
        "---\ntargets:\n  - claude\n---\n\n# Secret\n\nClaude only note.\n",
      );
      await runCli(["sync"], { cwd: dir, reporter: silent() });
      expect(await readFile(join(dir, "CLAUDE.md"), "utf8")).toContain("Secret");
      expect(await readFile(join(dir, "GEMINI.md"), "utf8")).not.toContain("Secret");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});

describe("map doctor (compiler checks)", () => {
  it("reports the compiler configuration as healthy after init", async () => {
    const dir = await tempProject();
    try {
      await runCli(["init", "--yes"], { cwd: dir, reporter: silent() });
      const reporter = capture();
      const code = await runCli(["doctor"], { cwd: dir, reporter });
      const out = reporter.lines.join("\n");
      expect(code).toBe(0);
      expect(out).toContain("compiler configured");
      expect(out).toContain("all targets map to a known adapter");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("fails when a target has no adapter", async () => {
    const dir = await tempProject();
    try {
      await runCli(["init", "--yes"], { cwd: dir, reporter: silent() });
      const configPath = join(dir, ".map/map.config.json");
      const config = JSON.parse(await readFile(configPath, "utf8"));
      config.targets = { bogus: { output: "X.md" } };
      await writeFile(configPath, JSON.stringify(config));

      const reporter = capture();
      const code = await runCli(["doctor"], { cwd: dir, reporter });
      expect(code).toBe(1);
      expect(reporter.lines.join("\n")).toContain("unsupported target(s): bogus");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
